version: "3.9"
services:
  fakes3:
    image: lphoward/fake-s3:latest
    ports:
      - "4569:4569"
    volumes:
      - ./data/s3root:/fakes3_root
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: dbpassword
    ports:
      - "5432:5432"
    volumes:
      - dev-pgdata:/var/lib/postgresql/data
volumes:
  dev-pgdata:
     external: true